### ISSUE TITLE
pytorch_android_torchaudio

### ISSUE THREAD

**Issue by dstrube1** [StevenJokes/pytorch-andriod-greatdemo#1]
Thank you for the very helpful tutorial! 
When I tried to add a reference to torchaudio, the build failed.
In build.gradle:
implementation 'org.pytorch:pytorch_android_torchaudio:1.4.0'
=>
Failed to resolve: org.pytorch:pytorch_android_torchaudio:1.4.0

Any suggestions?

**Comment by StevenJokes** [comment]
So sorry to reply so late. I just noticed that someone uses my tutorial, so happy!
And I found your stackflow here: https://stackoverflow.com/questions/63135485/how-to-use-pytorchs-torchaudio-in-android
You have got the answer!
